package types

// DB'den dönen item (id dahil)
type CartItem struct {
	ID        int `json:"id"`      // autogenerated by DB
	UserID    int `json:"user_id"` // inferred from JWT
	ProductID int `json:"product_id"`
	Quantity  int `json:"quantity"`
}

// Client'tan gelen istek (id gönderilmez)
type CartItemRequest struct {
	ProductID int `json:"product_id" example:"1"`
	Quantity  int `json:"quantity" example:"2"`
}
