basePath: /
definitions:
  types.CartItem:
    properties:
      product_id:
        type: integer
      quantity:
        type: integer
      user_id:
        type: integer
    type: object
  types.ItemResponse:
    properties:
      name:
        type: string
      quantity:
        type: integer
    type: object
  types.LoginRequest:
    properties:
      password:
        example: "123456"
        type: string
      username:
        example: john_doe
        type: string
    type: object
  types.Menu:
    properties:
      id:
        type: integer
      image_url:
        description: NEW
        type: string
      name:
        type: string
      price:
        type: number
      restaurant_id:
        type: integer
    type: object
  types.OrderItem:
    properties:
      product_id:
        type: integer
      quantity:
        type: integer
    type: object
  types.OrderResponse:
    properties:
      address:
        type: string
      id:
        type: integer
      items:
        items:
          $ref: '#/definitions/types.ItemResponse'
        type: array
      restaurant:
        type: string
      status:
        type: string
      total:
        type: string
      user:
        type: string
    type: object
  types.PlaceOrderRequest:
    properties:
      address:
        type: string
      items:
        items:
          $ref: '#/definitions/types.OrderItem'
        type: array
      restaurant_id:
        type: integer
    type: object
  types.RegisterRequest:
    properties:
      firstName:
        description: ⬅︎ değişti
        type: string
      lastName:
        description: ⬅︎ değişti
        type: string
      password:
        type: string
      username:
        type: string
    type: object
  types.Restaurant:
    properties:
      avg_price:
        type: integer
      cuisine:
        type: string
      description:
        type: string
      id:
        type: integer
      image_url:
        type: string
      location:
        type: string
      name:
        type: string
      rating:
        type: number
    type: object
  types.UpdateUserRequest:
    properties:
      first_name:
        type: string
      last_name:
        type: string
      password:
        type: string
      role_id:
        type: integer
      username:
        type: string
    type: object
  types.User:
    properties:
      created_at:
        type: string
      first_name:
        type: string
      id:
        type: integer
      last_name:
        type: string
      role_id:
        type: integer
      role_name:
        type: string
      username:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: RESTful API for restaurant ordering system
  title: SEProject API
  version: "1.0"
paths:
  /admin/restaurant:
    post:
      consumes:
      - multipart/form-data
      parameters:
      - description: Name
        in: formData
        name: name
        required: true
        type: string
      - description: Description
        in: formData
        name: description
        required: true
        type: string
      - description: Location
        in: formData
        name: location
        required: true
        type: string
      - description: Cuisine
        in: formData
        name: cuisine
        required: true
        type: string
      - description: Avg price
        in: formData
        name: avg_price
        required: true
        type: integer
      - description: Rating
        in: formData
        name: rating
        required: true
        type: number
      - description: Image file
        in: formData
        name: image
        required: true
        type: file
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/types.Restaurant'
        "400":
          description: bad
          schema:
            type: string
        "500":
          description: fail
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Create restaurant (multipart)
      tags:
      - Restaurant
  /admin/restaurant/{id}:
    delete:
      parameters:
      - description: Restaurant ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
        "400":
          description: bad
          schema:
            type: string
        "500":
          description: fail
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Delete restaurant
      tags:
      - Restaurant
    put:
      consumes:
      - application/json
      parameters:
      - description: Restaurant ID
        in: path
        name: id
        required: true
        type: integer
      - description: Restaurant info
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/types.Restaurant'
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
        "400":
          description: bad
          schema:
            type: string
        "500":
          description: fail
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Update restaurant
      tags:
      - Restaurant
  /admin/restaurant/{id}/image:
    put:
      consumes:
      - multipart/form-data
      parameters:
      - description: Restaurant ID
        in: path
        name: id
        required: true
        type: integer
      - description: Image file
        in: formData
        name: image
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: bad
          schema:
            type: string
        "500":
          description: fail
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Upload restaurant image
      tags:
      - Restaurant
  /cart:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/types.CartItem'
            type: array
        "500":
          description: fail
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Get current user's cart
      tags:
      - Cart
  /cart/add:
    post:
      consumes:
      - application/json
      parameters:
      - description: Cart item payload
        in: body
        name: item
        required: true
        schema:
          $ref: '#/definitions/types.CartItem'
      produces:
      - application/json
      responses:
        "201":
          description: ok
          schema:
            type: string
        "400":
          description: bad
          schema:
            type: string
        "500":
          description: fail
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Add item to cart
      tags:
      - Cart
  /delivery/orders:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/types.OrderResponse'
            type: array
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Kuryenin tüm siparişlerini listeler
      tags:
      - Delivery
  /login:
    post:
      consumes:
      - application/json
      description: Authenticates user and returns JWT
      parameters:
      - description: Login credentials
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/types.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Login user
      tags:
      - User
  /order/place:
    post:
      consumes:
      - application/json
      parameters:
      - description: Order payload
        in: body
        name: order
        required: true
        schema:
          $ref: '#/definitions/types.PlaceOrderRequest'
      produces:
      - application/json
      responses:
        "201":
          description: ok
          schema:
            type: string
        "400":
          description: bad
          schema:
            type: string
        "500":
          description: fail
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Place a new order
      tags:
      - Order
  /orders:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/types.OrderResponse'
            type: array
        "403":
          description: Forbidden
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: List all orders (admin)
      tags:
      - Order
  /register:
    post:
      consumes:
      - application/json
      description: Creates a new user with hashed password
      parameters:
      - description: User credentials
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/types.RegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Register a new user
      tags:
      - User
  /restaurant/menu:
    post:
      consumes:
      - multipart/form-data
      parameters:
      - description: Restaurant ID
        in: formData
        name: restaurant_id
        required: true
        type: integer
      - description: Name
        in: formData
        name: name
        required: true
        type: string
      - description: Price
        in: formData
        name: price
        required: true
        type: number
      - description: Image file
        in: formData
        name: image
        required: true
        type: file
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/types.Menu'
      security:
      - BearerAuth: []
      summary: Create menu item (multipart)
      tags:
      - Menu
  /restaurant/menu/{id}:
    delete:
      parameters:
      - description: Menu ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: ok
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Delete menu item
      tags:
      - Menu
    put:
      consumes:
      - application/json
      parameters:
      - description: Menu ID
        in: path
        name: id
        required: true
        type: integer
      - description: Data
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/types.Menu'
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Update menu item (name/price)
      tags:
      - Menu
  /restaurant/orders:
    get:
      parameters:
      - description: Restaurant ID
        in: query
        name: restaurant_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/types.OrderResponse'
            type: array
        "400":
          description: bad
          schema:
            type: string
        "500":
          description: fail
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: List orders for a restaurant
      tags:
      - Order
  /restaurant/orders/{id}/delivered:
    put:
      parameters:
      - description: Order ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
        "400":
          description: bad
          schema:
            type: string
        "500":
          description: fail
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Mark order as delivered
      tags:
      - Order
  /restaurant/orders/{id}/prepare:
    put:
      parameters:
      - description: Order ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
        "400":
          description: bad
          schema:
            type: string
        "500":
          description: fail
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Mark order as prepared
      tags:
      - Order
  /restaurants:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/types.Restaurant'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: List all restaurants
      tags:
      - Restaurant
  /restaurants/{rid}/menu:
    get:
      parameters:
      - description: Restaurant ID
        in: path
        name: rid
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/types.Menu'
            type: array
      summary: List menu items
      tags:
      - Menu
  /user:
    get:
      description: Get a user by providing their username
      parameters:
      - description: Username to search
        in: query
        name: username
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.User'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get user by username
      tags:
      - User
    post:
      consumes:
      - application/json
      description: Creates a new user in the system
      parameters:
      - description: User object
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/types.User'
      produces:
      - application/json
      responses:
        "201":
          description: User created
          schema:
            type: string
        "400":
          description: Invalid input
          schema:
            type: string
        "500":
          description: Failed to create user
          schema:
            type: string
      summary: Create a new user
      tags:
      - User
  /user/{id}:
    delete:
      description: Deletes a user by ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: User deleted
          schema:
            type: string
        "400":
          description: Invalid id
          schema:
            type: string
        "500":
          description: Failed to delete user
          schema:
            type: string
      summary: Delete user
      tags:
      - User
    put:
      consumes:
      - application/json
      description: Updates mutable user fields (username, password, first_name, last_name,
        role_id)
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      - description: Updatable fields
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/types.UpdateUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: User updated
          schema:
            type: string
        "400":
          description: Invalid id or input
          schema:
            type: string
        "500":
          description: Failed to update user
          schema:
            type: string
      summary: Update user
      tags:
      - User
  /user/all:
    get:
      description: Returns all users
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/types.User'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get all users
      tags:
      - User
  /user/me:
    get:
      consumes:
      - application/json
      description: Returns the currently authenticated user's info
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Get current user
      tags:
      - User
  /user/orders:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/types.OrderResponse'
            type: array
        "500":
          description: fail
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: List current user's orders
      tags:
      - Order
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
